package dev.segev.carpoolkids.model

/**
 * Shared carpool route document stored at carpool_routes/{practiceId}_{direction}.
 * Generated by the assigned driver and read in realtime by every group member.
 *
 * One document per (practice, direction) pair. PICKUP and DROPOFF are independent docs
 * because they have different owners, different roster realities, and regenerate separately.
 */
data class CarpoolRoute(
    val id: String,
    val groupId: String,
    val practiceId: String,
    /** [Constants.RouteDirection.PICKUP] or [Constants.RouteDirection.DROPOFF]. */
    val direction: String,
    val driverUid: String,
    val driverHomeLat: Double,
    val driverHomeLng: Double,
    val trainingLat: Double,
    val trainingLng: Double,
    /** Practice start ("HH:mm"), denormalized so the route screen renders without a second fetch. */
    val trainingStartTime: String,
    val trainingEndTime: String,
    val practiceDateMillis: Long,
    val stops: List<RouteStop> = emptyList(),
    /** Recommended departure (epoch millis). Pickup: start time − totalTravel − buffer. Dropoff: training end. */
    val recommendedDepartureMillis: Long = 0L,
    val totalDurationSec: Int = 0,
    val totalDistanceMeters: Int = 0,
    /** OSRM-encoded polyline (precision 5). Empty when [status] != READY. */
    val polyline: String = "",
    val polylinePrecision: Int = 5,
    /** [Constants.RouteStatus.*]. */
    val status: String,
    val failureReason: String? = null,
    val generatedAt: Long? = null,
    val generatedByUid: String? = null,
    /**
     * Phase 5 — uids of riders in [Practice.participantUids] who were skipped from this route
     * because they had no `homeLat/homeLng`. The route screen renders their names so the driver
     * can nudge them to set an address. Driver is never blocked by a missing address.
     */
    val missingAddressUids: List<String> = emptyList(),
    /** Optional Gemini summary; never required for routing correctness. */
    val aiSummary: String? = null,
    val aiSummaryGeneratedAt: Long? = null
)
